version: '3.7'

services:
  api:
    build:
        context: ./Taco.WebApi
        dockerfile: Dockerfile
    ports:
      - "5000:80"
    expose:
      - 5000
    command: dotnet Taco.WebApi.dll
    environment:
      ASPNETCORE_ENVIRONMENT: Devemolpment

  client_app:
    depends_on:
      - api
    build:
      context: ./Taco.ClientApp
    command: yarn start
    ports:
      - 3000:3000
    links:
      - api
    environment:
      REACT_APP_PUBLIC_URL: http://localhost:3000
      REACT_APP_API_URL: http://localhost:5000